### ISSUE TITLE
Footer Menu section - Phone view: Margins not justified 

### ISSUE THREAD

**Issue by Amalfi-Festival** [Amalfi-Festival/amalfi-festival-org#62]
On my phone the footer menu lines up as centered rather than left justified.

**Comment by zhangshichao0322** [comment]
I think it looks nicer being centered than left justified on the mobile devices?

**Comment by legion80** [comment]
This style was intentional. On mobile devices I switched it to center

<img width="518" alt="Screenshot 2024-01-21 at 9 39 26 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/8abec418-4d10-4f5b-9ecf-6b6c5c5bb09f">
<img width="321" alt="Screenshot 2024-01-21 at 9 39 44 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/3e8eab7f-4a70-4145-89d5-9bc3b23299ed">

Here's how it would look left-justified.

<img width="536" alt="Screenshot 2024-01-21 at 9 41 05 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/490700f7-d880-4108-9a90-48ced1cdb7ec">
<img width="321" alt="Screenshot 2024-01-21 at 9 40 43 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/7d95c925-62f3-4bad-85a3-b5f44e5a99e8">

I personally think the center justification looks better when the footer items have to be laid out vertically. But I can change it.

**Comment by zhangshichao0322** [comment]
Looking at how left-justified looks, I certainly prefer centered.  Leslie?

**Comment by Amalfi-Festival** [comment]
Okay, that's fine. Thanks.
