### ISSUE TITLE
Main page: text goes below the Ian's photo. 

### ISSUE THREAD

**Issue by zhangshichao0322** [Amalfi-Festival/amalfi-festival-org#67]
Is this intentional? Formatting is different on Teaching Seminar page, where texts are lined up. I think Teaching Seminar looks more neat. 

![IMG_8873](https://github.com/Amalfi-Festival/amalfi-festival-org/assets/147187405/e0615f76-d1ce-4df9-8524-6d5a5550cd48)

**Comment by legion80** [comment]
It kind of just fell this way. The original version of the home page, without pictures, had the text run all the way across the screen. It made it look like a wall of text and was a little intimidating to read. The pictures now break it up, but they are inset into the text, which is why when there's no more picture it goes all the way through.

You'll also notice that the paragraphs are not inset on the left side compared to the programs. They are aligned with the headers.

I think we can switch to the program layout now that we have these photos. The reason I didn't commit to it was that I thought if the text was sufficiently short a different, unique layout could be considered, like the piano page.

**Comment by zhangshichao0322** [comment]
I see! I just feel it's a little bit strange to have just one line under the photo, since we don't have much text now.  Perhaps it'd look nicer to have longer texts in the future, after Leslie adding something.

**Comment by legion80** [comment]
The photo of Jones is also relatively tall. Maybe we can try swapping, or even adding, the nicer version of the piano thunderstorm picture?

**Comment by legion80** [comment]
I sent a link to that picture in the thread

**Comment by zhangshichao0322** [comment]
Perhaps for the main page we can use photos that show groups? Rather than featuring one pianist. Perhaps concerts with audience, group dinner, excursion, etc.  And ideas?

**Comment by legion80** [comment]
I tried using the thunderstorm picture. Thoughts?
<img width="1089" alt="Screenshot 2024-01-21 at 11 06 00 AM" src="https://github.com/Amalfi-Festival/amalfi-festival-org/assets/83742/a38f3724-4409-4248-bc92-18bc2d379862">

**Comment by legion80** [comment]
Obsoleted by 46fb857
